// Generated by CoffeeScript 1.10.0
app.service("LocalVerseData", function($http, $stateParams, $q) {
  this.reload = (function(_this) {
    return function() {
      var audioDeffered, deffered;
      deffered = $q.defer();
      _this.verses = deffered.promise;
      audioDeffered = $q.defer();
      return $http.get("learn/" + $stateParams.itemId + ".json").success(function(data) {
        return deffered.resolve(data);
      });
    };
  })(this);
  return true;
});

//# sourceMappingURL=LocalVerseData.js.map
