// Generated by CoffeeScript 1.10.0
app.service("VerseLocalStorage", function($localStorage, $stateParams) {
  this.getState = function() {
    return $localStorage[$stateParams.itemId];
  };
  return false;
});

//# sourceMappingURL=VerseLocalStorage.js.map
