// Generated by CoffeeScript 1.8.0
var a, k, v, _i, _len;

a = {
  a: 1,
  b: 2,
  c: 3
};

for (k = _i = 0, _len = a.length; _i < _len; k = ++_i) {
  v = a[k];
  console.log("Key: " + k + " Value: " + v);
}

//# sourceMappingURL=__play.js.map
