// Generated by CoffeeScript 1.7.1
var History;

History = (function() {
  function History(historyData) {
    this.historyData = historyData;
  }

  History.prototype.add = function(listOfIncorrect) {
    var i, j, _i, _j, _len, _len1, _ref, _results;
    this.historyData.historyLength += 1;
    for (_i = 0, _len = listOfIncorrect.length; _i < _len; _i++) {
      i = listOfIncorrect[_i];
      this.historyData.history[i] += 1;
    }
    if (this.historyData.historyLength >= this.historyData.maxHistoryLength) {
      this.historyData.historyLength -= 1;
    }
    _ref = this.historyData.history;
    _results = [];
    for (j = _j = 0, _len1 = _ref.length; _j < _len1; j = ++_j) {
      i = _ref[j];
      if (j > 0) {
        _results.push(this.historyData.history[i] -= 1);
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

  History.prototype.colors = function() {
    var cssColor, i, wrong, _ref, _ref1;
    cssColor = {};
    if (this.historyData.historyLength > 0) {
      _ref = this.historyData.history;
      for (i in _ref) {
        wrong = _ref[i];
        cssColor[i] = "hsl(" + (116 * (1 - (wrong / this.historyData.historyLength))) + ", 100%, 45%)";
      }
    } else {
      _ref1 = this.historyData.history;
      for (i in _ref1) {
        wrong = _ref1[i];
        cssColor[i] = "#eee";
      }
    }
    return cssColor;
  };

  return History;

})();
